### PR TITLE
Revert Code Change

### LINKED ISSUE #774: [P0] Previous PR breaks testing mechanism
@subodh101 

Given your previous PR, you deleted [these files](https://github.com/kubeflow/testing/pull/771/files?file-filters%5B%5D=.py#diff-bbad93762216c61724e8720526f5263f2fe390737d1fec2a70736d7e19fd9afbL334-L401)

```
    # check if ks workflow and run	
    if w.app_dir:	
      ks_cmd = ks_util.get_ksonnet_cmd(w.app_dir)	

      # Print ksonnet version	
      util.run([ks_cmd, "version"])	

      # Create a new environment for this run	
      env = workflow_name	

      util.run([ks_cmd, "env", "add", env, "--namespace=" + get_namespace(args), "--api-spec=version:v1.8.0"],	
                cwd=w.app_dir)	

      util.run([ks_cmd, "param", "set", "--env=" + env, w.component,	
                "name", workflow_name],	
               cwd=w.app_dir)	

      # Set the prow environment variables.	
      prow_env = []	

      names = ["JOB_NAME", "JOB_TYPE", "BUILD_ID", "BUILD_NUMBER",	
               "PULL_BASE_SHA", "PULL_NUMBER", "PULL_PULL_SHA", "REPO_OWNER",	
               "REPO_NAME"]	
      names.sort()	
      for v in names:	
        if not os.getenv(v):	
          continue	
        prow_env.append("{0}={1}".format(v, os.getenv(v)))	

      util.run([ks_cmd, "param", "set", "--env=" + env, w.component, "prow_env",	
               ",".join(prow_env)], cwd=w.app_dir)	
      util.run([ks_cmd, "param", "set", "--env=" + env, w.component, "namespace",	
               get_namespace(args)], cwd=w.app_dir)	
      util.run([ks_cmd, "param", "set", "--env=" + env, w.component, "bucket",	
               args.bucket], cwd=w.app_dir)	
      if args.cloud_provider == "aws":	
        util.run([ks_cmd, "param", "set", "--env=" + env, w.component, "cluster_name",	
                "eks-cluster-{}".format(uuid.uuid4().hex[0:8])], cwd=w.app_dir)	
      if args.release:	
        util.run([ks_cmd, "param", "set", "--env=" + env, w.component, "versionTag",	
                  os.getenv("VERSION_TAG")], cwd=w.app_dir)	

      # Set any extra params. We do this in alphabetical order to make it easier to verify in	
      # the unittest.	
      param_names = w.params.keys()	
      if six.PY3:	
        # In python3, dict_keys.sort() not work given	
        # https://docs.python.org/3/whatsnew/3.0.html#views-and-iterators-instead-of-lists	
        param_names = sorted(param_names)	
      else:	
        param_names.sort()	
      for k in param_names:	
        util.run([ks_cmd, "param", "set", "--env=" + env, w.component, k,	
                 "{0}".format(w.params[k])], cwd=w.app_dir)	

      # For debugging print out the manifest	
      util.run([ks_cmd, "show", env, "-c", w.component], cwd=w.app_dir)	
      util.run([ks_cmd, "apply", env, "-c", w.component], cwd=w.app_dir)	

      if not args.cloud_provider or args.cloud_provider == "gcp":	
        ui_url = ("http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/{0}"	
                "?tab=workflow".format(workflow_name))	
      elif args.cloud_provider == "aws":	
        ui_url = ("http://86308603-argo-argo-5ce9-1162466691.us-west-2.elb.amazonaws.com/workflows/kubeflow-test-infra/{0}"	
                "?tab=workflow".format(workflow_name))	
      ui_urls[workflow_name] = ui_url	
      logging.info("URL for workflow: %s", ui_url)
```

This is used for most of the kubeflow WG, they haven't yet migrated to Tekton, this caused several test failure across different repos.

E.g, https://github.com/kubeflow/kubeflow/pull/5382
https://github.com/kubeflow/kfctl/pull/247

Can you revert these lines of code back?

### PR DESCRIPTION
**Pull request by PatrickXYS**
Resolve #774 

/cc @jlewi @Jeffwan  

This effects all the kubeflow repos which have not yet migrated to Tekton

### CODE REVIEW

**Review by andreyvelich — COMMENTED** [review]
/lgtm

**Comment by PatrickXYS** [comment]
/cc @subodh101 

I don't have access to the tekton pipeline UI, can you take a look?

**Comment by PatrickXYS** [comment]
/cc @jlewi 

Can you help on checking the Tekton Pipeline UI to see why it failed? Looks like I don't have access

https://kf-ci-v1.endpoints.kubeflow-ci.cloud.goog/tekton/#/namespaces/kf-ci/pipelineruns/py-unittests-zsr9w
https://kf-ci-v1.endpoints.kubeflow-ci.cloud.goog/tekton/#/namespaces/kf-ci/pipelineruns/go-test-hphsz

**Comment by jlewi** [comment]
@PatrickXYS You should be able to follow the README if you need to get access to the tekton UI.

**Comment by Jeffwan** [comment]
@PatrickXYS Can you try to revert all the changes to fix the test failures? We can bring back the entire change later.

**Comment by jlewi** [comment]
Here's the full error.

```
INFO|2020-11-04T16:22:35|/workspace/testing-repo/py/kubeflow/testing/tekton_client.py|400| Parsing JUNIT: junit_py-lint.xml
ERROR|2020-11-04T16:22:35|/workspace/testing-repo/py/kubeflow/testing/tekton_client.py|413| test_py_lint has failure: AssertionError: assert not ['/run_e2e_workflow.py']
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/workspace/testing-repo/py/kubeflow/testing/tekton_client.py", line 466, in <module>
    fire.Fire(CLI)
  File "/usr/local/lib/python2.7/dist-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python2.7/dist-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python2.7/dist-packages/fire/core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/testing-repo/py/kubeflow/testing/tekton_client.py", line 421, in junit_parse_and_upload
    "This task is failed with {0} errors/failures.".format(failed_num))
ValueError: This task is failed with 1 errors/failures.
```

**Comment by jlewi** [comment]
The test is indicating that the lint tests failed. If you look at the logs for lint.

```
py_lint_test.py             85 ERROR    1 files had lint errors:
/run_e2e_workflow.py
```

So the test is failing because after the revert run_e2e_workflow.py has lint changes.

**Comment by jlewi** [comment]
Here are the specific lint errors

```
util.py                     46 INFO     Running: pylint --rcfile=/workspace/testing-repo/.pylintrc /workspace/testing-repo/py/kubeflow/testing/run_e2e_workflow.py 
cwd=/workspace/testing-repo/py/kubeflow/testing
util.py                     61 INFO     Subprocess output:

util.py                     72 INFO     Using config file /workspace/testing-repo/.pylintrc
util.py                     72 INFO     ************* Module kubeflow.testing.run_e2e_workflow
util.py                     72 INFO     C:344, 0: Line too long (110/100) (line-too-long)
util.py                     72 INFO     C:398, 0: Line too long (115/100) (line-too-long)
```

**Comment by jlewi** [comment]
@PatrickXYS Join the ci-viewer-team to get get viewer access.
https://github.com/kubeflow/internal-acls/blob/master/google_groups/groups/ci-viewer.yaml

**Comment by PatrickXYS** [comment]
It works after I pylint some codes, if unit test is doing lint checking, it makes sense to add documentation for that.

/cc @Jeffwan  @jlewi 
Can you lgtm?

**Comment by Jeffwan** [comment]
image

Tekton results is confusing.  Green means completed but internally it does report error.. It would be great to reflect test errors in TaskRun status.

**Pull request merged**
