### PR TITLE
[AWS] Add test lifecycle

### PR DESCRIPTION
**Pull request by PatrickXYS**
**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**
Add test lifecycle to help users understand

**Checklist:**

If PR related to **Optional-Test-Infra**,
- [x] Changes need to be generated to `aws/GitOps` folder: 
    1. `cd aws`
    2. `make optional-generate`
    3. `make optional-test`

### CODE REVIEW

**Review by theofpa — CHANGES_REQUESTED** [review]
the image file is empty

**Comment by PatrickXYS** [comment]
This is weird, at the benginning I send PR, the image is there, but after 2-3 seconds, it disappeared.

**Comment by PatrickXYS** [comment]
image


The image is uploaded at the first glance

**Comment by PatrickXYS** [comment]
Oh though it shows empty files, the image is still there, you need to click "VIEW"

**Pull request merged**
