### PR TITLE
test(kfp): change access permission for kf-ci-v1-prow@kubeflow-ci.iam.gserviceaccount.com

### PR DESCRIPTION
**Pull request by capri-xiyue**
**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**
change access permission for kf-ci-v1-prow@kubeflow-ci.iam.gserviceaccount.com

**Checklist:**

If PR related to **Optional-Test-Infra**,
- [ ] Changes need to be generated to `aws/GitOps` folder: 
    1. `cd aws`
    2. `make optional-generate`
    3. `make optional-test`

### CODE REVIEW

**Comment by capri-xiyue** [comment]
staging permission issue gets resolved.

**Comment by Bobgy** [comment]
Great!
Thank you!
/lgtm
/approve

**Pull request merged**
