### PR TITLE
test(gcp): set up periodic cleanup of pipelineruns for kf-ci-v1. Fixes #750

### LINKED ISSUE #750: GC old tekton resources periodically
Discovered in https://github.com/kubeflow/gcp-blueprints/issues/128.

Currently all triggered `PipelineRun` and other tekton resources accumulate for ever.
We need to GC tekton resources.

Tekton community has an issue tektoncd/experimental#479 tracking this.
But there's no ready-to-use solution yet.

Before sth comes out of above issue, we should have at least a bash script that cleans up these resources.

### PR DESCRIPTION
**Pull request by Bobgy**
Fixes #750
/cc @PatrickXYS 
this can be useful for AWS test infra too

### CODE REVIEW

**Comment by Bobgy** [comment]
I'll self approve to quickly verify on GCP test infra

**Comment by Bobgy** [comment]
test infra seems flaky, I'll force merge this one

**Comment by Bobgy** [comment]
I got an error syncing the config:
```
kf-ci-v1   KNV1039: Cluster-scoped configs except Namespaces MUST be declared in `cluster/`. To fix, move the ClusterRole to `cluster/`.

source: namespaces/cleanup/rbac.authorization.k8s.io_v1_clusterrole_cleanup.yaml
namespace: cleanup
metadata.name: cleanup
group: rbac.authorization.k8s.io
version: v1
kind: ClusterRole
```

**Comment by PatrickXYS** [comment]
Thanks @Bobgy 

Looks like Tekton Pipeline doesn't support GC, which requires CronJobs to GC.

**Pull request merged**
