### PR TITLE
Updates for d.k.o; based on ks 0.11.0; params added

### PR DESCRIPTION
**Pull request by pdmack**
Various updates, but notably the Alibaba params

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/testing/157)

### CODE REVIEW

**Comment by ankushagarwal** [comment]
Has this been deployed to dev.kubeflow.org?

**Comment by pdmack** [comment]
Yes, yesterday.
```
Name:           tf-hub-0
Namespace:      kubeflow
Node:           gke-dev-cluster-cpu-pool-43c1bcd5-ptkm/10.128.0.4
Start Time:     Tue, 12 Jun 2018 17:39:15 -0400
....
```

**Comment by jlewi** [comment]
Review status: 0 of 26 files reviewed, 1 unresolved discussion (waiting on @pdmack, @zjj2wry, @ScorpioCPH, @jlewi, and @ankushagarwal)

---

*[dev-kubeflow-org/recreate_app.sh, line 104 at r1](https://reviewable.io/reviews/kubeflow/testing/157#-LEvQkfW78LPwViyY2ze:-LEvQkfW78LPwViyY2zf:b9j4ndc) ([raw file](https://github.com/kubeflow/testing/blob/ecce84c586f183a0428394501ac28c7afdb63681/dev-kubeflow-org/recreate_app.sh#L104)):*
> ```Shell
> ks param set kubeflow-core jupyterNotebookRepoName kubeflow-images-public --env=default
> 
> ks param set kubeflow-core tfAmbassadorImage quay.io/datawire/ambassador:0.30.1 --env=default
> ```

Why are we overriding the ambassador image? 
The parameter names also look wonky.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kubeflow/testing/157)*

**Comment by pdmack** [comment]
Review status: 0 of 26 files reviewed, 1 unresolved discussion (waiting on @pdmack, @zjj2wry, @ScorpioCPH, @jlewi, and @ankushagarwal)

---

*[dev-kubeflow-org/recreate_app.sh, line 104 at r1](https://reviewable.io/reviews/kubeflow/testing/157#-LEvQkfW78LPwViyY2ze:-LEv_hKlBPhStXi4A3VG:bm4btnm) ([raw file](https://github.com/kubeflow/testing/blob/ecce84c586f183a0428394501ac28c7afdb63681/dev-kubeflow-org/recreate_app.sh#L104)):*
<details><summary><i>Previously, jlewi (Jeremy Lewi) wrote…</i></summary><blockquote>

Why are we overriding the ambassador image? 
The parameter names also look wonky.
</blockquote></details>

Came in with the Alibaba changes:
`tfAmbassadorImage registry.aliyuncs.com/datawire/ambassador:0.34.0`

Also kubeflow/kubeflow#946

In general, I'm a little fuzzy on why we would set some things in recreate_app.sh vs. ks-app/components/params.libsonnet for d.k.o

---


*Comments from [Reviewable](https://reviewable.io/reviews/kubeflow/testing/157)*

**Comment by jlewi** [comment]
Review status: 0 of 26 files reviewed, 1 unresolved discussion (waiting on @jlewi, @zjj2wry, @ScorpioCPH, and @ankushagarwal)

---

*[dev-kubeflow-org/recreate_app.sh, line 104 at r1](https://reviewable.io/reviews/kubeflow/testing/157#-LEvQkfW78LPwViyY2ze:-LEwDAKb6J8TF5fDFWzu:brvgom0) ([raw file](https://github.com/kubeflow/testing/blob/ecce84c586f183a0428394501ac28c7afdb63681/dev-kubeflow-org/recreate_app.sh#L104)):*
<details><summary><i>Previously, pdmack (Pete MacKinnon) wrote…</i></summary><blockquote>

Came in with the Alibaba changes:
`tfAmbassadorImage registry.aliyuncs.com/datawire/ambassador:0.34.0`

Also kubeflow/kubeflow#946

In general, I'm a little fuzzy on why we would set some things in recreate_app.sh vs. ks-app/components/params.libsonnet for d.k.o
</blockquote></details>

We only need to override values for which the defaults don't match what we want for kubeflow.org

The defaults set here
https://github.com/kubeflow/kubeflow/blob/f6377404e032d036a8d78a91a25501dc9933499a/kubeflow/core/prototypes/all.jsonnet#L9

Should work fine for our case.

So you can revert these changes I think.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kubeflow/testing/157)*

**Comment by jlewi** [comment]
Review status: 0 of 26 files reviewed, 1 unresolved discussion (waiting on @jlewi, @zjj2wry, @ScorpioCPH, and @ankushagarwal)

---

*[dev-kubeflow-org/recreate_app.sh, line 104 at r1](https://reviewable.io/reviews/kubeflow/testing/157#-LEvQkfW78LPwViyY2ze:-LEwDVnz5YvoIvWrIBb9:bnevseb) ([raw file](https://github.com/kubeflow/testing/blob/ecce84c586f183a0428394501ac28c7afdb63681/dev-kubeflow-org/recreate_app.sh#L104)):*
<details><summary><i>Previously, jlewi (Jeremy Lewi) wrote…</i></summary><blockquote>

We only need to override values for which the defaults don't match what we want for kubeflow.org

The defaults set here
https://github.com/kubeflow/kubeflow/blob/f6377404e032d036a8d78a91a25501dc9933499a/kubeflow/core/prototypes/all.jsonnet#L9

Should work fine for our case.

So you can revert these changes I think.
</blockquote></details>

Specifically you don't need to set
tfStatsDImage
tfAmbassadorImage
jupyterNotebookRepoName
jupyterNotebookRegistry

---


*Comments from [Reviewable](https://reviewable.io/reviews/kubeflow/testing/157)*

**Comment by pdmack** [comment]
Review status: 0 of 26 files reviewed, 1 unresolved discussion (waiting on @pdmack, @zjj2wry, @ScorpioCPH, @jlewi, and @ankushagarwal)

---

*[dev-kubeflow-org/recreate_app.sh, line 104 at r1](https://reviewable.io/reviews/kubeflow/testing/157#-LEvQkfW78LPwViyY2ze:-LEwGtj79to9_qOK_W-C:b1p63dy) ([raw file](https://github.com/kubeflow/testing/blob/ecce84c586f183a0428394501ac28c7afdb63681/dev-kubeflow-org/recreate_app.sh#L104)):*
<details><summary><i>Previously, jlewi (Jeremy Lewi) wrote…</i></summary><blockquote>

Specifically you don't need to set
tfStatsDImage
tfAmbassadorImage
jupyterNotebookRepoName
jupyterNotebookRegistry
</blockquote></details>

Nope. If we don't set these:

`ERROR find objects: RUNTIME ERROR: Field does not exist: jupyterNotebookRegistry`

---


*Comments from [Reviewable](https://reviewable.io/reviews/kubeflow/testing/157)*

**Comment by jlewi** [comment]
Review status: 0 of 26 files reviewed, 1 unresolved discussion (waiting on @jlewi, @zjj2wry, @ScorpioCPH, and @ankushagarwal)

---

*[dev-kubeflow-org/recreate_app.sh, line 104 at r1](https://reviewable.io/reviews/kubeflow/testing/157#-LEvQkfW78LPwViyY2ze:-LEycfTI0pyTn5KDJgG8:b-58m65y) ([raw file](https://github.com/kubeflow/testing/blob/ecce84c586f183a0428394501ac28c7afdb63681/dev-kubeflow-org/recreate_app.sh#L104)):*
<details><summary><i>Previously, pdmack (Pete MacKinnon) wrote…</i></summary><blockquote>

Nope. If we don't set these:

`ERROR find objects: RUNTIME ERROR: Field does not exist: jupyterNotebookRegistry`
</blockquote></details>

So that is telling you that those parameters aren't defined inside params.
They need to be defined here:
https://reviewable.io/reviews/kubeflow/testing/157

But the default parameters in params.libsonnet are created when we call ks generate using the values specified in the prototype.

So when we call ks generate kubeflow-core params.libsonnet should automatically get a dictionary of params for kubeflow-core with all the default parameters set to the values listed in the libsonnet file.

This is what we want. The only parameters inside recreate_app.sh should be the values we want to explicitly override because we want different values then the default for dev.kubeflow.org

If you delete the component kubeflow-core (you will need to manually delete the corresponding dictionary of params in params.libsonnet) and then run ks generate that should initialize the params.libsonnet correctly

Alternatively if you delete dev.kubeflow.org and rerun the script after removing these lines I think that will also work.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kubeflow/testing/157)*

**Pull request merged**
