### PR TITLE
Allow test on Katib release branches

### PR DESCRIPTION
**Pull request by andreyvelich**
**Which issue is resolved by this Pull Request:**
Related: https://github.com/kubeflow/katib/issues/1774.

**Description of your changes:**
This PR allows tests on Katib release-0.13 branch

/assign @capri-xiyue @zijianjoy
/cc @gaocegege @johnugeorge

**Checklist:**

If PR related to **Optional-Test-Infra**,
- [x] Changes need to be generated to `aws/GitOps` folder: 
    1. `cd aws`
    2. `make optional-generate`
    3. `make optional-test`

### CODE REVIEW

**Comment by zijianjoy** [comment]
Will it make sense to use `branches: ^master|release-.*$` ? So you don't need to create new PR every time.

**Comment by zijianjoy** [comment]
Taking a prow example from another repo: https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-postsubmits.yaml#L6

**Comment by andreyvelich** [comment]
> Taking a prow example from another repo: https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-postsubmits.yaml#L6

That makes sense, thanks!
I've made changes.

**Pull request merged**
