### PR TITLE
Use snapshot files to checkout repositories.

### PR DESCRIPTION
**Pull request by gabrielwen**
Relates to #95 

This part uses output of #297 and checkout source codes from Github for deployment.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/testing/298)

### CODE REVIEW

**Comment by kunmingg** [comment]
Do you need to do ```git config user.email```?
otherwise
/lgtm

**Comment by gabrielwen** [comment]
> Do you need to do `git config user.email`?
> otherwise
> /lgtm

ran and it works.  I think you only need to mention user.email if you clone with SSH?

**Comment by kunmingg** [comment]
Got it 
/approve

**Pull request merged**
