### PR TITLE
Add ssh to test-worker

### PR DESCRIPTION
**Pull request by ankushagarwal**
It was removed in https://github.com/kubeflow/testing/pull/36/files

Related https://github.com/kubeflow/testing/issues/112

/cc @pdmack 
/cc @lluunn

### CODE REVIEW

**Comment by pdmack** [comment]
@ankushagarwal we're pretty sure nothing else important got lost? Asking for a friend...

**Comment by ankushagarwal** [comment]
Hard to say. Let's merge this and see if all tests pass in kubeflow/kubeflow

**Pull request merged**
