### PR TITLE
Only consider include_dirs on presubmit tests; install funcsigs.

### LINKED ISSUE #196: pytests failing ImportError: No module named funcsigs
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kubeflow_testing/195/kubeflow-testing-presubmit/347/

```
INFO|2018-08-23T03:22:24|util.py:62| Traceback (most recent call last):
INFO|2018-08-23T03:22:25|util.py:62| File "/mnt/test-data-volume/kubeflow-testing-presubmit-unittests-195-cdae8ff-347-73c7/src/kubeflow/testing/py/kubeflow/tests/run_e2e_workflow_test.py", line 3, in <module>
INFO|2018-08-23T03:22:25|util.py:62| import mock
INFO|2018-08-23T03:22:25|util.py:62| File "/usr/local/lib/python2.7/dist-packages/mock/__init__.py", line 2, in <module>
INFO|2018-08-23T03:22:25|util.py:62| import mock.mock as _mock
INFO|2018-08-23T03:22:25|util.py:62| File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 80, in <module>
INFO|2018-08-23T03:22:25|util.py:62| import funcsigs
INFO|2018-08-23T03:22:25|util.py:62| ImportError: No module named funcsigs
INFO|2018-08-23T03:22:26|util.py:41| Running: python /mnt/test-data-volume/kubeflow-testing-presubmit-unittests-195-cdae8ff-347-73c7/src/kubeflow/testing/py/kubeflow/tests/test_util_test.py 
cwd=/mnt/test-data-volume/kubeflow-testing-presubmit-unittests-195-cdae8ff-347-73c7/src/kubeflow/testing/py/kubeflow/tests
INFO|2018-08-23T03:22:26|util.py:56| Subprocess output:
```

I just upgraded the test worker image so that could be related.

New image:
gcr.io/kubeflow-ci/test-worker:v20180822-d8bc7c8-e3b0c4 

Confirmed that in that image the import is broken.
Note its using python2.7 not python3.

### PR DESCRIPTION
**Pull request by jlewi**
* We all tests to be triggered only when certain files are modified.
* I think it only makes sense to apply this filter on presubmits; for
  postsubmits we should include always run a test.

* Update funcsigs in the testing image otherwise the import of mock is broken; Fix #196 
Related to: kubeflow/kubeflow#1048

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/testing/195)

### CODE REVIEW

**Comment by richardsliu** [comment]
Could you also update the README file?

**Comment by jlewi** [comment]
Done.

**Pull request merged**
