### PR TITLE
use 2to3 to convert from Python2 to 3 and use yapf to reformat

### LINKED ISSUE #44: Verify python code is formatted with yapf
In kubeflow/tf-operator#401 we started using yapf to enforce a consistent Python style.

We should a presubmit test so that we can ensure all python code is properly formatted.

/cc @Jimexist

### PR DESCRIPTION
**Pull request by Jimexist**
_low priority_

use:

- 2to3 to convert for python3 code style
- use `yapf` to auto format code
- fixes #44

### CODE REVIEW

**Comment by Jimexist** [comment]
the benefict / cost for this PR is a bit low so it is really low priority for now. I am just submitting for view only.

**Comment by jlewi** [comment]
Please sync. Can you pick a reviewer (other than me :)) I'd like to start spreading the review workload around.

**Comment by Jimexist** [comment]
to be merged after #36

**Comment by Jimexist** [comment]
seems like the presubmit job is a bit unstable for now

**Comment by Jimexist** [comment]
@jlewi any idea why the link gave by bot was invalid?

**Comment by jlewi** [comment]
@Jimexist If you see that error

```
Unable to load build details from gs://kubernetes-jenkins/pr-logs/pull/kubeflow_testing/35/kubeflow-testing-presubmit/56
```

It typically means the prow job didn't make it as far as actually uploading any results to GCS.

So typically in this case you can trigger the test and then look for the job in the prow job dashboard. From there you can grab the actual pod logs. These get garbage collected pretty soon after the job finishes so you need to try to catch it in the act.

**Comment by jlewi** [comment]
Here's the link to the prow jobs dashboard
https://prow.k8s.io/?repo=kubeflow%2Ftesting

**Comment by Jimexist** [comment]
seems like https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kubeflow_testing/35/kubeflow-testing-presubmit/64/ is not found

**Comment by jlewi** [comment]
Most likely that means there is a problem running the workflow and it never gets far enough to upload the results to GCS.

You need to try to look at the pod logs for the test; these are ephmeral so you need to grab them shortly after running your job.

You can find them here
https://prow.k8s.io/?repo=kubeflow%2Ftesting

**Comment by Jimexist** [comment]
@jlewi maybe due to lack of authorization, what i saw in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/kubeflow_testing/35/kubeflow-testing-presubmit/99/ was:

> 
Unable to load build details from gs://kubernetes-jenkins/pr-logs/pull/kubeflow_testing/35/kubeflow-testing-presubmit/99

**Comment by jlewi** [comment]
I was able to get access to the logs. Here's the failure

```
"Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/src/kubeflow/testing/py/kubeflow/testing/run_e2e_workflow.py", line 36, in <module>
    from kubeflow.testing import argo_client
  File "/src/kubeflow/testing/py/kubeflow/testing/argo_client.py", line 9, in <module>
    from kubeflow.testing import util
  File "/src/kubeflow/testing/py/kubeflow/testing/util.py", line 10, in <module>
    import urllib.request, urllib.parse, urllib.error
ImportError: No module named request
```

**Comment by Jimexist** [comment]
see https://github.com/kubeflow/testing/pull/86 in leu of

**Pull request closed without merging**
