### PR TITLE
Report for test flakiness 

### PR DESCRIPTION
**Pull request by zabbasi**
#355

Validated the report. 

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/testing/356)

 Need to validate report.

### CODE REVIEW

**Comment by jlewi** [comment]
@zabbasi How's this coming?

**Comment by jlewi** [comment]
Thanks!
/ok-to-test

**Comment by zabbasi** [comment]
> @zabbasi How's this coming?

Looks like Kettle only reads Junit tests artifacts. is it enough?

**Pull request merged**
