### PR TITLE
Create a python3.8 version of the worker image

### PR DESCRIPTION
**Pull request by jlewi**
* Related to kubeflow/testing#560 - python3 lint
* We need this because we need a newer (3.8) version of pylint
  to allow for python3.8 syntax like f strings.

* In this pass we eschewed the following packages which I don't think we
  need anymore

  * ksonnet
  * helm
  * glide (should be using go modules and staged builds)
  * docker
  * nodejs (should be using staged builds)

* Create a skaffold config to build the image.

* Related to: kubeflow/kfctl#228 endpoint test is failing

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/testing/606)

### CODE REVIEW

**Comment by jlewi** [comment]
Running pylint in the docker image

```
pylint --version
pylint 2.4.4
astroid 2.3.3
Python 3.8.0 (default, Oct 28 2019, 16:14:01) 
[GCC 8.3.0]
```

**Comment by zhenghuiwang** [comment]
Using Python3.8 and Ubuntu 18.04 is great! 

Do we need to apt-get these packages (build-essential \cmake \ curl etc) as before?

**Comment by jlewi** [comment]
@gabrielwen added gcloud

@zhenghuiwang curl is already there; I don't think we use cmake anywhere. I'm not sure if we need build-essential. If we are building binaries  We use make and that's already installed. What's in build-essential?

**Comment by jlewi** [comment]
@gabrielwen any additional comments?

**Comment by gabrielwen** [comment]
no
/lgtm

**Pull request merged**
