### PR TITLE
Add kserve for testing

### PR DESCRIPTION
**Pull request by yuzisun**
**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**
This is for testing purpose in kserve github org.

**Checklist:**

If PR related to **Optional-Test-Infra**,
- [x] Changes need to be generated to `aws/GitOps` folder: 
    1. `cd aws`
    2. `make optional-generate`
    3. `make optional-test`

### CODE REVIEW

**Comment by theofpa** [comment]
@yuzisun we need the 

```
cd aws
make optional-generate
make optional-test
```
To make the test pass

**Comment by yuzisun** [comment]
> @yuzisun we need the
> 
> ```
> cd aws
> make optional-generate
> make optional-test
> ```
> 
> To make the test pass

done!

**Comment by yuzisun** [comment]
@PatrickXYS can you help add @theofpa to the aws infra owner file and approve this?

**Comment by PatrickXYS** [comment]
@theofpa  You can file a PR to add yourself into OWNERS and I can help approve

**Comment by theofpa** [comment]
> @theofpa You can file a PR to add yourself into OWNERS and I can help approve

thanks for your support @PatrickXYS , raised #954

**Comment by PatrickXYS** [comment]
Apart from the PR, I remember as another github organization, kserve need to add bot account with at least write access, and add corresponding webhook.

**Comment by yuzisun** [comment]
> Apart from the PR, I remember as another github organization, kserve need to add bot account with at least write access, and add corresponding webhook.

@PatrickXYS is that `aws-kf-ci-bot`, also which webhook I need to setup?

**Comment by PatrickXYS** [comment]
@yuzisun  Thanks for adding, can you follow this doc to add webhook in kserve/kserve. 

https://docs.google.com/document/d/19hK0aPQGHI1LRFcdgS00Dihd4t6B2GRsjSNIGCZUxaw/edit.

Please request access if not able to access the doc

**Comment by yuzisun** [comment]
> https://docs.google.com/document/d/19hK0aPQGHI1LRFcdgS00Dihd4t6B2GRsjSNIGCZUxaw/edit.

@PatrickXYS Thanks! I have requested the access.

**Pull request merged**
