### PR TITLE
adding Python3 support in Dockerfile as well

### PR DESCRIPTION
**Pull request by Jimexist**
related: https://github.com/tensorflow/k8s/pull/378

### CODE REVIEW

**Comment by Jimexist** [comment]
@jlewi I see that so far there's no CI. I suggest adding CircleCI to build this Dockerfile just to cvheck.

**Comment by Jimexist** [comment]
```
Sending build context to Docker daemon  12.29kB

Step 1/20 : FROM ubuntu:xenial
 ---> 0458a4468cbc
Step 2/20 : MAINTAINER Jeremy Lewi
 ---> Using cache
 ---> 75a0b6f52c06
Step 3/20 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 380e47634b17
Step 4/20 : ENV TERM linux
 ---> Using cache
 ---> d4559f5334fa
Step 5/20 : RUN set -ex     && apt-get update -yqq     && apt-get install -yqq --no-install-recommends         curl         locales         wget         ca-certificates         git         zip         unzip         gcc         python-dev         python-setuptools         python-pip         python3-dev         python3-setuptools         python3-pip     && python -V     && python3 -V     && apt-get clean     && rm -rf         /var/lib/apt/lists/*         /tmp/*         /var/tmp/*         /usr/share/man         /usr/share/doc         /usr/share/doc-base
 ---> Using cache
 ---> 9be6bb05fb8a
Step 6/20 : RUN cd /tmp &&     wget -O /tmp/go.tar.gz https://redirector.gvt1.com/edgedl/go/go1.9.2.linux-amd64.tar.gz &&     tar -C /usr/local -xzf go.tar.gz
 ---> Using cache
 ---> 57d6658ef307
Step 7/20 : ENV PATH=/usr/local/go/bin:/google-cloud-sdk/bin:/workspace:${PATH}     CLOUDSDK_CORE_DISABLE_PROMPTS=1
 ---> Using cache
 ---> 0078ab542357
Step 8/20 : RUN wget -q https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz &&     tar xzf google-cloud-sdk.tar.gz -C / &&     rm google-cloud-sdk.tar.gz &&     /google-cloud-sdk/install.sh         --disable-installation-options         --bash-completion=false         --path-update=false         --usage-reporting=false &&     gcloud components install alpha beta kubectl
 ---> Using cache
 ---> c7b45938ce51
Step 9/20 : RUN wget -O /tmp/get_helm.sh     https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get &&     chmod 700 /tmp/get_helm.sh &&     /tmp/get_helm.sh &&     rm /tmp/get_helm.sh
 ---> Using cache
 ---> 6d295a4ce676
Step 10/20 : RUN helm init --client-only
 ---> Using cache
 ---> cd2a5f4b5207
Step 11/20 : RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -     && apt-get install -y nodejs
 ---> Using cache
 ---> 224a73049f20
Step 12/20 : RUN curl -sS http://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -     && echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list     && apt-get update -yqq     && apt-get install -yqq --no-install-recommends yarn
 ---> Using cache
 ---> 34ff98473bb2
Step 13/20 : RUN cd /tmp &&     wget -O glide-v0.13.0-linux-amd64.tar.gz             https://github.com/Masterminds/glide/releases/download/v0.13.0/glide-v0.13.0-linux-amd64.tar.gz &&     tar -xvf glide-v0.13.0-linux-amd64.tar.gz &&     mv ./linux-amd64/glide /usr/local/bin/
 ---> Using cache
 ---> 34679898618d
Step 14/20 : RUN cd /tmp &&     wget -O ks.tar.gz     https://github.com/ksonnet/ksonnet/releases/download/v0.8.0/ks_0.8.0_linux_amd64.tar.gz  &&     tar -xvf ks.tar.gz &&     mv ks_0.8.0_linux_amd64/ks /usr/local/bin &&     chmod a+x /usr/local/bin/ks
 ---> Using cache
 ---> 20ebf2a75a5e
Step 15/20 : COPY ./requirements.txt /tmp/requirements.txt
 ---> Using cache
 ---> 18a6f94560c7
Step 16/20 : RUN pip install -U pip wheel &&     pip install -r /tmp/requirements.txt &&     pip3 install -U pip wheel &&     pip3 install -r /tmp/requirements.txt
 ---> Using cache
 ---> d91dcf68b070
Step 17/20 : COPY checkout.sh /usr/local/bin
 ---> Using cache
 ---> b999c8a77699
Step 18/20 : RUN chmod a+x /usr/local/bin/checkout.sh
 ---> Using cache
 ---> 7d7370435c25
Step 19/20 : ENV USER root
 ---> Using cache
 ---> c8e5f8b374b0
Step 20/20 : ENV PYTHONPATH /src/kubeflow/testing/py
 ---> Using cache
 ---> fac7f94cc747
Successfully built fac7f94cc747
Successfully tagged testing:latest
```

**Comment by Jimexist** [comment]
```sh
docker image ls testing
```
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
testing             latest              fac7f94cc747        2 minutes ago       1.6GB
```

**Comment by Jimexist** [comment]
@jlewi if you don't mind enabling CircleCI builds for this repo then I can do the configuration for building docker as well. But I guess similar things can be done for GCE but I am less familiar with that. You call.

**Comment by Jimexist** [comment]
when this image is ready we can enable it by just swaping `python` with `python3` in https://github.com/tensorflow/k8s/blob/master/test/workflows/components/workflows.libsonnet#L217-L226

**Comment by jlewi** [comment]
@Jimexist I was thinking we would use Prow + Argo to continuously build and test our Docker images.

**Comment by jlewi** [comment]
See kubeflow/testing#19

**Pull request merged**
