### PR TITLE
Automate new project creation

### PR DESCRIPTION
**Pull request by zhenghuiwang**
This PR adds scripts and configurations to automate the project creation on GCP. These projects can be later used by load test or end-to-end test.

Tested this PR by using it to create [a project](https://pantheon.corp.google.com/kubernetes/list?project=kf-gcp-deploy-test5&organizationId=&angularJsUrl=%2Fkubernetes%2Flist%3Fsupportedpurview%3Dproject%26project%3Dkf-gcp-deploy-test5%26organizationId%3D&folder=&supportedpurview=project).

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/testing/318)

### CODE REVIEW

**Comment by jlewi** [comment]
Thanks @zhenghuiwang is this related to some issue?

IIRC the intent was to create a bunch of projects to use for load testing click to deploy?

**Comment by zhenghuiwang** [comment]
> Thanks @zhenghuiwang is this related to some issue?
> 
> IIRC the intent was to create a bunch of projects to use for load testing click to deploy?

Yes, it is for the load testing click-to-deploy. I just created a issue https://github.com/kubeflow/kubeflow/issues/2580

**Pull request merged**
