### PR TITLE
Update set values tests

### PR DESCRIPTION
**Pull request by subodh101**
What?

As per the title.

Why?

The process of setting kfp values has been changed due to redundant variables.

### CODE REVIEW

**Comment by jlewi** [comment]
@subodh101 You should join the GitHub org so that you can trigger the tests.

**Comment by subodh101** [comment]
Error:

```
mkdir -p /mnt/test-data-volume/kubeflow-testing-presubmit-py-unittests-759-147a73e-4864-5bbb/src/kubeflow
mkdir: cannot create directory ‘/mnt/test-data-volume/kubeflow-testing-presubmit-py-unittests-759-147a73e-4864-5bbb’: No space left on device
```

**Comment by subodh101** [comment]
Seems like the capacity `5Gi` of the pvc `nfs-external` has been reached.

**Comment by subodh101** [comment]
@Bobgy Could you help me delete some of the old directories as mentioned https://github.com/kubeflow/testing/blob/master/playbook/playbook.md#deleting-old-directories-on-the-nfs-share

Cluster: kubeflow-testing (namespace: kubeflow-test-infra)

`gcloud --project=kubeflow-ci container clusters --zone=us-east1-d get-credentials kubeflow-testing`

```
kubectl exec -it debug-worker-0 /bin/bash
Error from server (Forbidden): pods "debug-worker-0" is forbidden: User "subodh.pushkar@gmail.com" cannot create resource "pods/exec" in API group "" in the namespace "kubeflow-test-infra": requires one of ["container.pods.exec"] permission(s).
```
Also, I am having a little difficulty in checking the `disk usage`.

**Comment by jlewi** [comment]
@subodh101 My preference would be to fix the issue by migrating our tests to use Tekton and eliminate the use of NFS; #769

NFS filling up has been a constant headache; so rather than doing a patch fix I think we might be better served by coming up with a more permanent solution even if it takes longer. Any chance you could pick up #769?

**Comment by Bobgy** [comment]
/lgtm
Thanks for the fix!

**Pull request merged**
