### PR TITLE
Added gsoc label to kubeflow_label.yml

### PR DESCRIPTION
**Pull request by sarahmaddox**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/testing/623)

### CODE REVIEW

**Comment by jlewi** [comment]
@sarahmaddox I would suggest changing the label to "area/gsoc"

The main reason is that this will allow the label to be added via chat-bot commands as you can see from my comment above. This works for area labels but not community labels.

**Comment by sarahmaddox** [comment]
Thanks @jlewi PTAL.

**Pull request merged**
