### PR TITLE
Tekton pipeline client should use generate name

### PR DESCRIPTION
**Pull request by jlewi**
* Use generateName to generate names for pipelines; we can use labels
  to attach semantic/metadata information to the pipeline.

Related to #682: tekton_client.py submitting pipelineruns with names that
 are too long

### CODE REVIEW

**Comment by jlewi** [comment]
/assign @Bobgy 

/assign @IronPan 
/assign @Ark-kun 

@Ark-kun or @IronPan would one of you mind doing a quick review of this? I need these changes to be merged to see if it fixes the issues with the Tekton pipelines. Its 4am right now in Shanghai so @Bobgy won't be around for a while.

**Comment by Ark-kun** [comment]
/lgtm
There seem to be many extra changes in this PR...

**Comment by jlewi** [comment]
@Ark-kun Mostly cleanup related to testing the original change

* Replacing ArgParser with Fire made it easy to add an entrypoint to allow running `tekton_client.py` locally which was one of the easiest ways to test it
* Likewise adding python3 support to run_e2e_workflow.py made it easier to run locally 
* Improved the exception handling in retries to print out the stack trace because retry logic was making it hard to see where the error was actually occuring.

**Pull request merged**
