### PR TITLE
upgrade tornado to fix fairing e2e test failing

### PR DESCRIPTION
**Pull request by jinchihe**
Upgrade tornado to fix integration test failure https://github.com/kubeflow/fairing/issues/336 in Kubeflow Fairing.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/testing/432)

### CODE REVIEW

**Comment by jlewi** [comment]
Is it possible to update the E2E tests in this repo to use the new image so that we know its working.
maybe if we set it here
https://github.com/kubeflow/testing/blob/52615d4bb26558db7d6f5abcac20aebac465a99c/workflows/components/workflows.libsonnet#L37

**Comment by jinchihe** [comment]
/close

The problem has been fixed in the Fairing, thanks.

**Pull request closed without merging**
