### PR TITLE
Fix python3.8 and pip linking

### LINKED ISSUE #760: Pip link to wrong python version
Working on the e2e test cases. 

I notice there are two python version in the test image.  
```
ls /usr/loca
l/lib/python3.*
/usr/local/lib/python3.6:
dist-packages

/usr/local/lib/python3.8:
dist-packages

```

Checking Dockerfile, there's an issue on the python and pip installation. 

https://github.com/kubeflow/testing/blob/db508d70b7181a6f53afb7ed8d3de469f27abaab/images/Dockerfile.py3#L7-L9

https://github.com/kubeflow/testing/blob/db508d70b7181a6f53afb7ed8d3de469f27abaab/images/Dockerfile.py3.aws#L7-L9

`apt-get install python3-pip ` install python3.6 actually.  `pip` is linked to python3.6 env. 

```
pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
```

We linked python3.8 to `/usr/bin/python`,  however, python3 points to python3.6. 
```
$ python3 --version
Python 3.6.9

$ which python3
/usr/bin/python3
```

So if you use pip3(3.6) to install requirement and use `pytest` (3.8) to run tests, you will package can not be imported issue. 

```
root@400794f84897:/# apt-get install python3-pip 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  binutils binutils-common binutils-x86-64-linux-gnu build-essential ca-certificates cpp cpp-7 dbus dh-python dirmngr dpkg-dev
  fakeroot file g++ g++-7 gcc gcc-7 gcc-7-base gir1.2-glib-2.0 gnupg gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client
  gpg-wks-server gpgconf gpgsm libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl libapparmor1 libasan4
  libasn1-8-heimdal libassuan0 libatomic1 libbinutils libc-dev-bin libc6-dev libcc1-0 libcilkrts5 libdbus-1-3 libdpkg-perl
  libexpat1 libexpat1-dev libfakeroot libfile-fcntllock-perl libgcc-7-dev libgdbm-compat4 libgdbm5 libgirepository-1.0-1
  libglib2.0-0 libglib2.0-data libgomp1 libgssapi3-heimdal libhcrypto4-heimdal libheimbase1-heimdal libheimntlm0-heimdal
  libhx509-5-heimdal libicu60 libisl19 libitm1 libkrb5-26-heimdal libksba8 libldap-2.4-2 libldap-common liblocale-gettext-perl
  liblsan0 libmagic-mgc libmagic1 libmpc3 libmpdec2 libmpfr6 libmpx2 libnpth0 libperl5.26 libpython3-dev libpython3-stdlib
  libpython3.6 libpython3.6-dev libpython3.6-minimal libpython3.6-stdlib libquadmath0 libreadline7 libroken18-heimdal
  libsasl2-2 libsasl2-modules libsasl2-modules-db libsqlite3-0 libssl1.1 libstdc++-7-dev libtsan0 libubsan0 libwind0-heimdal
  libxml2 linux-libc-dev make manpages manpages-dev mime-support netbase openssl patch perl perl-modules-5.26 pinentry-curses
  python-pip-whl python3 python3-asn1crypto python3-cffi-backend python3-crypto python3-cryptography python3-dbus python3-dev
  python3-distutils python3-gi python3-idna python3-keyring python3-keyrings.alt python3-lib2to3 python3-minimal
  python3-pkg-resources python3-secretstorage python3-setuptools python3-six python3-wheel python3-xdg python3.6 python3.6-dev
  python3.6-minimal readline-common shared-mime-info xdg-user-dirs xz-utils

```

### PR DESCRIPTION
**Pull request by Jeffwan**
resolve #760 

1. Delete `python3-pip` and python3.6 won't be installed
2. Link pip3/pip to python3.8
3. Link python3 to python3.8

### CODE REVIEW

**Comment by jlewi** [comment]
/lgtm
/approve

Might want to fix the OWNERs files so others can approve these.

**Comment by PatrickXYS** [comment]
Sounds good, I'll send a new PR to add OWNERs file as well.

**Pull request merged**
