### PR TITLE
use prow_config if exists

### PR DESCRIPTION
**Pull request by lluunn**
Check prow_config.yaml exists before loading it.

We will add config_file arg for kubeflow/kubeflow in https://github.com/kubeflow/kubeflow/pull/275

### CODE REVIEW

**Comment by jlewi** [comment]
This won't work as expected.

I think you want to modify
https://github.com/kubeflow/kubeflow/blob/master/testing/run.sh

And then rebuild the Docker image
https://github.com/kubeflow/kubeflow/tree/master/testing

That's because our prow config isn't using the generic worker image yet.

We need to update our prow configs to do that.

**Comment by jlewi** [comment]
Hang on. May have spoken two hastily.

**Comment by jlewi** [comment]
I think I was correct.
See
kubeflow/kubeflow#279

**Comment by lluunn** [comment]
https://github.com/kubeflow/kubeflow/pull/275 modifies run.sh.
If that looks good, I will then update the image.

**Comment by lluunn** [comment]
related https://github.com/kubeflow/kubeflow/issues/276#event-1485784512

**Comment by lluunn** [comment]
Update https://github.com/kubeflow/kubeflow/pull/275 as suggested. Doesn't need this change.

**Pull request closed without merging**
